@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

class "{abstract}\nCommand" as Command
class FindCommand

package "Parser classes" {
    class "<<interface>>\nParser" as Parser
    class AddressBookParser
    class FindCommandParser
    class CliSyntax
    class ArgumentMultimap
    class ArgumentTokenizer
    class Prefix
}

class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> FindCommandParser : <<create>>

FindCommandParser ..> FindCommand : <<create>>
AddressBookParser ..> Command : <<use>>
FindCommandParser .up.|> Parser

FindCommandParser ..> CliSyntax
FindCommandParser ..> ArgumentMultimap
FindCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
ArgumentTokenizer .down.> Prefix

FindCommand -up-|> Command
@enduml
