@startuml
!include style.puml
skinparam ArrowFontStyle plain

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":CommandBox" as CommandBox UI_COLOR
participant ":ResultDisplay" as ResultDisplay UI_COLOR
participant ":PersonListPanel" as PersonListPanel UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "f:FindCommand" as FindCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> CommandBox : handleCommandEntered()
activate CommandBox

CommandBox -> MainWindow : executeCommand("find n/john")
activate MainWindow

MainWindow -> LogicManager : execute("find n/john")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("find n/john")
activate AddressBookParser

create FindCommandParser
AddressBookParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> AddressBookParser
deactivate FindCommandParser

AddressBookParser -> FindCommandParser : parse(" n/john")
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand --> FindCommandParser : f
deactivate FindCommand

FindCommandParser --> AddressBookParser : f
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> AddressBookParser
destroy FindCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FindCommand : execute(m)
activate FindCommand

FindCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model

Model --> FindCommand
deactivate Model

FindCommand -> Model : getAddressBook()
activate Model

Model --> FindCommand
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand
deactivate CommandResult

FindCommand --> LogicManager : r
deactivate FindCommand

LogicManager --> MainWindow : r
deactivate LogicManager

MainWindow -> PersonListPanel : refreshHeaderLabels()
PersonListPanel --> MainWindow

MainWindow -> ResultDisplay : setFeedbackToUser(r.feedback)
activate ResultDisplay
ResultDisplay --> MainWindow
deactivate ResultDisplay

opt r.foundPersons is present and not empty
    MainWindow -> ResultDisplay : setPersonList(r.foundPersons)
    activate ResultDisplay
    ResultDisplay --> MainWindow
    deactivate ResultDisplay
end

MainWindow --> CommandBox
deactivate MainWindow

[<-- CommandBox
deactivate CommandBox
@enduml
